In [2]:
import utils
path = r"data/link_prediction/facebook/edges.txt"
nodes = []
with open(path) as f:
    for line in f.readlines():
        # print(line.strip().split()[:2])
        nodes.extend(line.strip().split()[:2])
        # break
print(set(nodes[0]))
print(nodes[0])
# nodes = sorted(list(set(nodes)))
print(len(nodes))
print(nodes[0])
for new_id , old_id in enumerate(nodes):
    print(new_id)
    print(old_id)
    break

{'0'}
0
176468
0
0
0


In [26]:
import torch
A = torch.arange(20).resize(5 , 4)
A = A.sum(dim=0)
print(torch.cumsum(A , dim=0))

print(torch.cumsum(A , dim=0)[:-1])
print(torch.cat([torch.tensor([0]) , torch.cumsum(A , dim=0)[:-1]]))
tm = torch.cat([torch.tensor([0]) , torch.cumsum(A , dim=0)[:-1]])
tm = tm.unsqueeze(1)
print(tm)

tensor([ 40,  85, 135, 190])
tensor([ 40,  85, 135])
tensor([  0,  40,  85, 135])
